export const softwares = [
  { name: 'Linux', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/linux-tux-1.svg' },
  { name: 'Firefox', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/firefox-3.svg' },
  { name: 'VLC Media Player', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/vlc-media-player.svg' },
  { name: 'GIMP', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/gimp.svg' },
  { name: 'Blender', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/blender-2.svg' },
  { name: 'LibreOffice', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/libreoffice.svg' },
  { name: 'WordPress', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/wordpress-blue.svg' },
  { name: 'Git', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/git-icon.svg' },
  { name: 'Docker', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/docker.svg' },
  { name: 'Kubernetes', type: 'open-source', logo: 'https://cdn.worldvectorlogo.com/logos/kubernetes.svg' },
  { name: 'Windows', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/microsoft-windows-22.svg' },
  { name: 'Microsoft Office', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/microsoft-office-2013.svg' },
  { name: 'Adobe Photoshop', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/adobe-photoshop-cs6.svg' },
  { name: 'macOS', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/macos.svg' },
  { name: 'iOS', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/ios-2.svg' },
  { name: 'AutoCAD', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/autocad.svg' },
  { name: 'Slack', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/slack-new-logo.svg' },
  { name: 'Zoom', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/zoom-communications-logo.svg' },
  { name: 'Spotify', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/spotify-1.svg' },
  { name: 'Netflix', type: 'proprietary', logo: 'https://cdn.worldvectorlogo.com/logos/netflix-3.svg' },
];
